# Generated by Django 2.2 on 2019-08-11 16:41

from collections import Counter

from django.db import migrations


def forwards_func(apps, _):
    User = apps.get_model("users", "User")

    lower_usernames = [username.lower() for username in User.objects.values_list('username', flat=True)]
    duplicates = [
        username for (username, count)
        in Counter(lower_usernames).items()
        if count > 1
    ]
    if duplicates:
        raise Exception('Невозможно провести миграцию, следующие username не уникальны {}'.format(duplicates))

    for user in User.objects.all():
        user.username = user.username.lower()
        user.save(update_fields=['username'])


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
