# Generated by Django 2.2.1 on 2019-10-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190811_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='draft_viewer',
            field=models.BooleanField(default=False),
        ),
    ]
