# Generated by Django 2.2 on 2019-04-21 13:01

from django.db import migrations

from events.interfaces import ActivityType


def extract_talks(apps, _):
    Activity = apps.get_model('events', 'Activity')
    Talk = apps.get_model('talks', 'Talk')
    Speaker = apps.get_model('talks', 'Speaker')
    for activity in Activity.objects.filter(type=ActivityType.TALK).iterator():
        print(activity.name)
        splitted = activity.name.split(' / ')
        if len(splitted) > 1:
            first_name, last_name = splitted[1].strip().split(' ')
            speaker = Speaker.objects.create(first_name=first_name, last_name=last_name)
        else:
            speaker = Speaker.objects.create(first_name='undefined', last_name='undefined')
        Talk.objects.create(activity=activity, title=splitted[0].strip(), description='description', speaker=speaker)


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(extract_talks)
    ]
