# Generated by Django 2.2 on 2019-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_vk',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
