# Generated by Django 2.2.1 on 2019-05-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190430_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cfp_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cfp_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cfp_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
