# Generated by Django 2.2.1 on 2019-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190507_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
