# Generated by Django 2.2.1 on 2019-05-16 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_zone_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='events.Venue'),
        ),
    ]
