# Generated by Django 2.2.1 on 2019-07-21 13:53

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import events.interfaces


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190623_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', django_enumfield.db.fields.EnumField(default=0, enum=events.interfaces.PartnerType)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('link', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='events.Event')),
            ],
        ),
    ]
