# Generated by Django 2.2.1 on 2019-08-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190516_0531'),
        ('events', '0009_partner'),
    ]

    operations = [
    ]
