# Generated by Django 2.2.1 on 2019-08-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_merge_20190811_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='discussion_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='discussion_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
