# Generated by Django 2.2.1 on 2019-10-28 08:21

import django_enumfield.db.fields
from django.db import migrations

import events.interfaces


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190818_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('view_draft', 'Can view the draft event')]},
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=events.interfaces.EventStatusType),
        ),
    ]
