# Generated by Django 2.2 on 2019-04-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='full_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='undefined', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(default='undefined', max_length=30),
            preserve_default=False,
        ),
    ]
