# Generated by Django 2.2.1 on 2019-08-16 08:11

from django.db import migrations


def email_lower(apps, _):
    Order = apps.get_model('checkout', 'Order')
    Ticket = apps.get_model('checkout', 'Ticket')
    for Model in (Order, Ticket):
        for item in Model.objects.iterator():
            item.email = item.email.lower()
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20190815_2059'),
    ]

    operations = [
        migrations.RunPython(email_lower, migrations.RunPython.noop)
    ]
