# Generated by Django 2.2.1 on 2019-11-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20190820_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qticket_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qticket_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
