# Generated by Django 2.2.1 on 2020-09-07 18:23

import career.enums
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('placement', django_enumfield.db.fields.EnumField(default=0, enum=career.enums.PlacementType)),
                ('address', models.CharField(max_length=200, null=True)),
                ('employment', django_enumfield.db.fields.EnumField(default=0, enum=career.enums.EmploymentType)),
                ('link', models.URLField(null=True)),
                ('start_cost', models.PositiveIntegerField()),
                ('finish_cost', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
