# Generated by Django 2.2.16 on 2020-11-01 17:56

import career.enums
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('level', enumfields.fields.EnumField(enum=career.enums.LevelType, max_length=10)),
                ('practice', enumfields.fields.EnumField(enum=career.enums.PracticeType, max_length=10)),
                ('placement', enumfields.fields.EnumField(enum=career.enums.PlacementType, max_length=10)),
                ('address', models.CharField(max_length=200, null=True)),
                ('employment', enumfields.fields.EnumField(enum=career.enums.EmploymentType, max_length=10)),
                ('link', models.URLField(null=True)),
                ('start_cost', models.PositiveIntegerField()),
                ('finish_cost', models.PositiveIntegerField()),
                ('contacts', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', enumfields.fields.EnumField(default='active', enum=career.enums.VacancyStatus, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
