# Generated by Django 2.2.1 on 2020-09-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'technologies',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title',
            field=models.CharField(default='NULL', max_length=120),
            preserve_default=False,
        ),
    ]
