# Generated by Django 2.2.1 on 2020-09-11 01:03

import career.enums
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20200911_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=career.enums.VacancyStatus),
        ),
    ]
