# Generated by Django 2.1.7 on 2019-04-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('work', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Activity')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talks.Speaker')),
                ('poster', models.URLField()),
                ('presentation_offline', models.URLField(null=True, blank=True)),
                ('presentation_online', models.URLField(null=True, blank=True)),
                ('video', models.URLField(null=True, blank=True)),
            ],
        ),
    ]
