# Generated by Django 2.2.1 on 2019-06-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_talk_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL('UPDATE talks_talk t SET event_id = (SELECT event_id FROM events_activity a WHERE t.activity_id = a.id)'),
    ]
