# Generated by Django 2.2.1 on 2019-05-16 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.interfaces


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190516_0531'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0002_talk_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Activity')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussions', to=settings.AUTH_USER_MODEL)),
                ('votes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(events.interfaces.ActivityInterface, models.Model),
        ),
    ]
