# Generated by Django 2.2.1 on 2019-08-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_discussion'),
        ('talks', '0004_talk_poster_image'),
    ]

    operations = [
    ]
