# Generated by Django 2.2.1 on 2019-08-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_merge_20190811_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event'),
        ),
    ]
