# Generated by Django 2.2.1 on 2019-10-29 01:50

from django.db import migrations


def move_speakers(apps, _):
    Talk = apps.get_model('talks', 'Talk')
    for talk in Talk.objects.iterator():
        talk.speakers.add(talk.speaker)
        talk.save()


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_auto_20191029_0138'),
    ]

    operations = [
        migrations.RunPython(move_speakers)
    ]
