# Generated by Django 2.2.1 on 2019-10-29 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_merge_20190811_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(related_name='speakers', to='talks.Speaker'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event'),
        ),
    ]
