# Generated by Django 2.2.1 on 2019-10-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='speaker',
        ),
    ]
